CLASS zcl_06_airplane_log_c363 DEFINITION ABSTRACT
  PUBLIC
  "FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
      airplane_type ABSTRACT
        RETURNING VALUE(rv_airplane_type) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_airplane_log_c363 IMPLEMENTATION.
ENDCLASS.
